import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :the_adventuring_day, TheAdventuringDayWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: TheAdventuringDay.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, :console, format: "[$level] $message\n"

config :phoenix, :stacktrace_depth, 20

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :the_adventuring_day,
       :random_table_collection_repo,
       TheAdventuringDay.Infrastructure.Persistence.RandomTableCollectionRepo

config :the_adventuring_day,
       :enemy_template_spec_repo,
       TheAdventuringDay.Infrastructure.Persistence.EnemyTemplateSpecRepo

config :the_adventuring_day,
       :terrain_features_repo,
       TheAdventuringDay.Infrastructure.Persistence.TerrainFeaturesRepo

config :the_adventuring_day,
       :hazard_features_repo,
       TheAdventuringDay.Infrastructure.Persistence.HazardFeaturesRepo
